### ISSUE TITLE
数据获取

### ISSUE THREAD

**Issue by kangzhang0709** [layumi/AICIty-reID-2020#14]
你好，想问一下数据怎么获取呢？我看官网数据获取需要密码。你那边可以共享一下吗？

**Comment by miraclebiu** [comment]
> 你好，想问一下数据怎么获取呢？我看官网数据获取需要密码。你那边可以共享一下吗？

数据是属于官方的，需要根据官方的指导进行获取

**Comment by kangzhang0709** [comment]
> > 你好，想问一下数据怎么获取呢？我看官网数据获取需要密码。你那边可以共享一下吗？
> 
> 数据是属于官方的，需要根据官方的指导进行获取
