### ISSUE TITLE
Missing pkl features

### ISSUE THREAD

**Issue by alvarogm84** [layumi/AICIty-reID-2020#15]
Could you please provide all the necessay features in order to run the fast_submit_baidu.py?
For example the "query_fea_ResNeXt101_vd_64x4d_cos_alldata_final.pkl" is missing

**Comment by layumi** [comment]
Thanks @alvarogm84 
I will check the feature again and upload it soon. Thank you very much.

**Comment by layumi** [comment]
I have updated the feature. You may download from [GoogleDrive](https://drive.google.com/file/d/1_S1RnnP2fK3wQ68DsSAiFJYvyqzh55_d/view?usp=sharing) or [OneDrive](https://studentutsedu-my.sharepoint.com/:u:/g/personal/12639605_student_uts_edu_au/EebBIatfjE9Nksrl9UQGfQ4B5DIFem7DbJu9i2erpSZ1IQ?e=ukKcuZ)

**Comment by alvarogm84** [comment]
Thanks for your quick response, but there are still missing files, those files that imply both query and gallery versions: 
query_path.replace('query', 'gallery'))

Only the query version are available

**Comment by layumi** [comment]
Sorry. It is my mistake. I have updated the feature. You may download from [GoogleDrive](https://drive.google.com/file/d/1q0ap5smXoRIQ-oEUMbSMMSl_lEOT0Fk6/view?usp=sharing) or [OneDrive](https://studentutsedu-my.sharepoint.com/:u:/g/personal/12639605_student_uts_edu_au/EdxlWLP9bB9Bga0jfDyoIO8BoArp7CU72iXPfaNbM8cRuw?e=KS20JX)

**Comment by alvarogm84** [comment]
Thanks!
