### ISSUE TITLE
13个模型特征合并

### ISSUE THREAD

**Issue by HanwenCao** [layumi/AICIty-reID-2020#20]
郑博士您好，在fast_submit.py 中将query_feature0~query_feature12合并作为最终的特征。请问只有feature0是pytorch这边的吗？

**Comment by HanwenCao** [comment]
我看论文并没有描述这13个模型之间的区别（有可能是我没找到），还请郑博士指教~

**Comment by layumi** [comment]
是的。模型是lrRate的差异和训练数据有些加了生成的区别，文章没办法说清楚。做比赛大家一起弄，细节可能有些偏差，所以写的大多数是公约数。
