### ISSUE TITLE
代码中cluster含义

### ISSUE THREAD

**Issue by HanwenCao** [layumi/AICIty-reID-2020#23]
https://github.com/layumi/AICIty-reID-2020/blob/6a8e5da2e531566ea26f122f05f94b4a0265593d/pytorch/fast_submit_baidu.py#L321-L356

请问郑博士，这一部分代码是在做什么？谢谢！

**Comment by HanwenCao** [comment]
前一部分似乎是对应论文中的Query Expansion？论文说的不太清晰，Query Expansion 究竟是在做什么？谢谢

**Comment by layumi** [comment]
@HanwenCao 
你可以看看这一篇文章
https://arxiv.org/pdf/1711.02512.pdf
