### ISSUE TITLE
ff = torch.FloatTensor(n,512).zero_().cuda() 

### ISSUE THREAD

**Issue by vokhidovhusan** [layumi/AICIty-reID-2020#38]
Hi @layumi 
sorry for bothering you. May I ask you again?
```pyhton
def extract_feature(/*...*/):    
   // ...
    for data in tqdm(dataloaders):
        //...
        ff = torch.FloatTensor(n,512).zero_().cuda()
```
Where did 512 come from ? 
I am curious about the reason why you set the parameter as 512.

**Comment by layumi** [comment]
Hi @martianvenusian ,
It is the dimension of the feature before the classification layer. 
https://github.com/layumi/AICIty-reID-2020/blob/master/pytorch/model.py#L43
